name: 'Check Branch'

on:
  pull_request:
    branches: [production]

jobs:
  build:
    name: Check branch
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'production' && github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge to production from develompent."
          exit 1
